#! /bin/sh

dir=$PWD
cd `dirname $0`
files=`pwd -L`
ln -snFv $files/.bashrc $HOME/.bashrc
ln -snFv $files/.bash_profile $HOME/.bash_profile
ln -snFv $files/.Xdefaults $HOME/.Xdefaults
ln -snFv $files/.tmux.conf $HOME/.tmux.conf
ln -snfv $files/.ctags $HOME/.ctags
ln -snFv $files/.cvsignore $HOME/.cvsignore
ln -snFv $files/.vim $HOME/.vim
ln -snFv $files/.tmux $HOME/.tmux
ln -snFv $files/.vimrc $HOME/.vimrc
ln -snFv $files/.irbrc $HOME/.irbrc
ln -snFv $files/.gemrc $HOME/.gemrc
ln -snFv $files/bin $HOME
git submodule init
git submodule update --recursive
cd $dir
