let $VIMDIR="$HOME/.vim"
let $RC="$HOME/.vim/vimrc"

set nocompatible
set noerrorbells
set visualbell
set backspace=indent,eol,start
set history=1000

set laststatus=2
set showcmd
set showmode
set ruler
set number
set wildmenu

set hidden
set autoread


filetype plugin indent on
syntax on

set path=.,**
set nowrap
set textwidth=79
set shiftwidth=4 tabstop=4
set autoindent
set exrc
set modeline
set undofile
set undodir=~/.cache/vim/undo
set directory=~/.cache/vim/swp//
set backupdir=~/.cache/vim/backup//

set scrolloff=3
set sidescrolloff=5

set background=dark
set t_Co=256 " XXX vim-sensible will set this to 8 if unset without a $TERM!

set incsearch ignorecase smartcase hlsearch
nnoremap <Esc><Esc> :nohlsearch<CR>

set mouse=a
" Plugins {{{
packadd sensible " Sane defaults (in case I forgot any from above)
packadd polyglot " Additional language settings
packadd sleuth " Autodetected buffer settings
packadd commentary " Better commenting
packadd surround " For changing brackets, quotes, etc
packadd projectionist " Honour a project-wide .projectionist.json
packadd repeat " Make . work more often
packadd abolish " Work with variants of words
packadd apathy " Set some miscellaneous path vars
packadd endwise " Adds `ends` to languages where it makes sense
packadd unimpaired " Handy [] mappings
" Language specific plugins
packadd crystal " crystal
packadd go " golang
packadd rake " ruby
packadd rust " rust
" LSP and auto-linting
" packadd lsc " Language Server Client (natebosch/vim-lsc)
" packadd mucomplete " Minimalistic autocompleter (lifepillar/mucomplete)
" packadd ale " Asynchronous Linting Engine (dense-analysis/ale)
" packadd lsp " Language Server Protocol (prabirshrestha/vim-lsp)
" packadd lspale " LSP for ALE (rhysd/vim-lsp-ale)
" Add-ons
packadd emmet " Web snippets
packadd eunuch "UNIX commands
packadd dadbod " DB front-end
packadd kubectl " Kubectl front-end
packadd fugitive " Git front-end
packadd fzf " Fuzzy finder 🙂
packadd goyo " Focused text
packadd limelight " Even more focused text
" Themes {{{
packadd gruvbox
packadd dracula
packadd jellybeans
packadd iceberg
packadd solarized
" }}}

colorscheme iceberg
highlight StatusLine ctermbg=none cterm=bold

" Emoji digraphs
execute 'digraph :x 128544'
execute 'digraph :) 128578'
execute 'digraph :D 128512'
execute 'digraph =D 128513'
execute 'digraph :P 128523'
execute 'digraph :O 128558'
execute 'digraph :/ 128533'
execute 'digraph :( 128577'
execute 'digraph =( 128543'
execute 'digraph :E 128556'
execute 'digraph /\ 128591'
execute 'digraph \/ 129335'
execute 'digraph :\| 128528'
execute 'digraph =\| 128529'
execute 'digraph -k 128070'
execute 'digraph -j 128071'
execute 'digraph -h 128072'
execute 'digraph -l 128073'
execute 'digraph [b 128161'
execute 'digraph [w 128075'
" vi:sw=4:ts=4:tw=80
